services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env
  
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hive-metastore:
    image: apache/hive:4.0.0-beta-1
    container_name: hive-metastore
    restart: always
    depends_on:
      - postgres
    environment:
      - SERVICE_NAME=hivemetastore
      - DB_DRIVER=postgres
      - DB_USER=hive
      - DB_PASS=hive
      - DB_HOST=postgres
      - DB_PORT=5433
      - DB_NAME=metastore
    ports:
      - "9083:9083"
    volumes:
      - ./hive/conf:/opt/hive/conf
    command: /opt/hive/bin/hive --service metastore

  hive-server:
    image: apache/hive:4.0.0-beta-1
    container_name: hive-server
    restart: always
    depends_on:
      - hive-metastore
      - namenode
      - datanode1
      - datanode2
    environment:
      - SERVICE_NAME=hiveserver2
      - DB_DRIVER=postgres
      - DB_USER=hive
      - DB_PASS=hive
      - DB_HOST=postgres
      - DB_PORT=5433
      - DB_NAME=metastore
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./hive/conf:/opt/hive/conf
    command: /opt/hive/bin/hive --service hiveserver2

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  postgres_data: